###### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Bobert",
  "email": "bobert@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "bobert@test.com",
  "password": "password"
}

### Dogs create
POST http://localhost:3000/dogs.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NzExMzU1OTd9.pCtFGyRutClEHC8c1TfNtRjtpkgUJnpajRK5ec2r21I
Content-Type: application/json

{
  "name": "Spike",
  "age": "2",
  "breed": "Bulldog"
}

